sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t thomasvan/docker-react -f Dockerfile.dev .

script:
    - docker run  -e CI=true thomasvan/docker-react npm run test
